title: Zizzla
description: Bye car, thanks for the ride

#google_analytics:

# Contacts
email: anders.dalen@zizzla.com
#twitter_username:

repository: zizzla/zizzla.github.io

# Build settings
plugins:
  - jekyll-feed
  - jekyll-sitemap
